        .text

        .xref   Blocks

        .data

Blocks:

        .dc.b   %0000
        .dc.b   %1111
        .dc.b   %0000
        .dc.b   %0000

        .dc.b   %0100
        .dc.b   %0100
        .dc.b   %0100
        .dc.b   %0100

        .dc.b   %0000
        .dc.b   %0000
        .dc.b   %1111
        .dc.b   %0000

        .dc.b   %0010
        .dc.b   %0010
        .dc.b   %0010
        .dc.b   %0010


        .dc.b   %0010
        .dc.b   %0010
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %1110
        .dc.b   %0010
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0100
        .dc.b   %0100

        .dc.b   %0000
        .dc.b   %0100
        .dc.b   %0111
        .dc.b   %0000


        .dc.b   %0100
        .dc.b   %0100
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0010
        .dc.b   %1110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0010
        .dc.b   %0010

        .dc.b   %0000
        .dc.b   %0111
        .dc.b   %0100
        .dc.b   %0000


        .dc.b   %0000
        .dc.b   %0011
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0100
        .dc.b   %0110
        .dc.b   %0010

        .dc.b   %0000
        .dc.b   %0011
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0100
        .dc.b   %0110
        .dc.b   %0010


        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0011
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0010
        .dc.b   %0110
        .dc.b   %0100

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0011
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0010
        .dc.b   %0110
        .dc.b   %0100


        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0110
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0110
        .dc.b   %0110
        .dc.b   %0000


        .dc.b   %0111
        .dc.b   %0010
        .dc.b   %0000
        .dc.b   %0000

        .dc.b   %0010
        .dc.b   %0011
        .dc.b   %0010
        .dc.b   %0000

        .dc.b   %0000
        .dc.b   %0010
        .dc.b   %0111
        .dc.b   %0000

        .dc.b   %0001
        .dc.b   %0011
        .dc.b   %0001
        .dc.b   %0000


; Killer-Stein

		.dc.b	%0000
		.dc.b	%0010
		.dc.b	%0000
		.dc.b	%0000

		.dc.b	%0000
		.dc.b	%0010
		.dc.b	%0000
		.dc.b	%0000

		.dc.b	%0000
		.dc.b	%0010
		.dc.b	%0000
		.dc.b	%0000

		.dc.b	%0000
		.dc.b	%0010
		.dc.b	%0000
		.dc.b	%0000
		

        .end

