/* Resource Datei Indizes fÅr KUBRSC */

#define NEWSCORE         0   /* Formular/Dialog */
#define TNAME            2   /* FTEXT in Baum NEWSCORE */
#define ABBRUCH          3   /* BUTTON in Baum NEWSCORE */
#define OK               4   /* BUTTON in Baum NEWSCORE */
#define NSTITLE          5   /* STRING in Baum NEWSCORE */
#define NSNENTER         6   /* STRING in Baum NEWSCORE */

#define SCORES           1   /* Formular/Dialog */
#define SCLINE1          5   /* STRING in Baum SCORES */
#define SC1              6   /* TEXT in Baum SCORES */
#define SCLINE2          8   /* STRING in Baum SCORES */
#define SC2              9   /* TEXT in Baum SCORES */
#define SCLINE3          11  /* STRING in Baum SCORES */
#define SC3              12  /* TEXT in Baum SCORES */
#define SCLINE4          14  /* STRING in Baum SCORES */
#define SC4              15  /* TEXT in Baum SCORES */
#define SCLINE5          17  /* STRING in Baum SCORES */
#define SC5              18  /* TEXT in Baum SCORES */
#define SCLINE6          20  /* STRING in Baum SCORES */
#define SC6              21  /* TEXT in Baum SCORES */
#define SCLINE7          23  /* STRING in Baum SCORES */
#define SC7              24  /* TEXT in Baum SCORES */
#define SCCOPY           25  /* BUTTON in Baum SCORES */
#define SCOK             26  /* BUTTON in Baum SCORES */

#define HELP             2   /* Formular/Dialog */
#define HLEFT            18  /* STRING in Baum HELP */
#define HTLEFT           19  /* STRING in Baum HELP */
#define HTRIGHT          20  /* STRING in Baum HELP */
#define HRIGHT           21  /* STRING in Baum HELP */
#define HDROP            22  /* STRING in Baum HELP */
#define HPAUSE           23  /* STRING in Baum HELP */
#define HCLOSEW          24  /* STRING in Baum HELP */
#define HEND             25  /* STRING in Baum HELP */
